### ISSUE TITLE
TODO/FIXME Count 5

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-web-vc-store#6]
- [ ] throw new Error('FIXME: Out of date');
       Commit: (c4835af) Partial updates for edv-client support.
       File:  [test/web/mock.js:16](https://github.com/digitalbazaar/bedrock-web-vc-store/blob/master/test/web/mock.js#L16)
       Dave Longley commented 6 months ago

  - [ ] TODO: add some static data to test against
       Commit: (786ca2a) Update to use latest bedrock-web-data-hub API.
       File:  [test/web/mock.js:13](https://github.com/digitalbazaar/bedrock-web-vc-store/blob/master/test/web/mock.js#L13)
       Dmitri Zagidulin commented a year ago

  - [ ] FIXME: Very out of date, needs to be updated to work with
       Commit: (c4835af) Partial updates for edv-client support.
       File:  [test/web/mock.js:10](https://github.com/digitalbazaar/bedrock-web-vc-store/blob/master/test/web/mock.js#L10)
       Dave Longley commented 6 months ago

  - [ ]TODO: Change code to use spread operator when bedrock-karma is fixed
      Commit: (ad8c5c2) Finish initial implementation of credential store.
      Fi[test/web/10-VerifiableCredentialStore.test.js:115](https://github.com/digitalbazaar/bedrock-web-vc-store/blob/master/test/web/10-VerifiableCredentialStore.test.js#L115)
      Ganesh Annan commented a year ago

  - [ ] FIXME: there is special behavior here that the Mock* classes rely on;
       Commit: (786ca2a) Update to use latest bedrock-web-data-hub API.
       File:  [test/web/mock.js:22](https://github.com/digitalbazaar/bedrock-web-vc-store/blob/master/test/web/mock.js#L22)
       Dmitri Zagidulin commented a year ago

       FIXME Count         3
       TODO Count          2
       Oldest Comment      a year ago
       Oldest Commenter    Dmitri Zagidulin
       Oldest Comment      TODO: add some static data to test against

**Comment by dlongley** [comment]
All FIXMEs and TODOs addressed or removed from code.
